---
- name: Execute composer install
  shell: composer install chdir=/share

- name: Excecute php artisan migrate
  shell: php artisan migrate chdir=/share

- name: Execute php artisan db:seed
  shell: php artisan db:seed chdir=/share

